param(
    [string]$Root = "."
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path $Root).Path
. (Join-Path $repoRoot "scripts/skills-lib.ps1")

$skills = Get-SkillFiles -RepoRoot $repoRoot | ForEach-Object {
    Get-SkillFrontmatter -Path $_.FullName -RepoRoot $repoRoot
}

$orderedCategories = Get-SkillCategoryOrder
$lines = New-Object System.Collections.Generic.List[string]
$roleGroups = [ordered]@{
    entrypoint = @()
    workflow   = @()
    specialist = @()
}

$lines.Add("# Skill Index")
$lines.Add("")
$lines.Add('> Auto-generated by `scripts/generate-skills-index.ps1`. Do not edit manually.')
$lines.Add("")
$lines.Add("本目录包含当前项目可用的全部 Skills，用于辅助代码生成、规范约束与自动化决策。")
$lines.Add("")
$lines.Add("当前共收录 **$($skills.Count)** 个 skills，覆盖 **$($orderedCategories.Count)** 个分类。")
$lines.Add("")
$lines.Add("## Quick Navigation")
$lines.Add("")

foreach ($category in $orderedCategories) {
    $group = $skills | Where-Object { $_.Frontmatter["category"] -eq $category }
    if ($group) {
        $meta = Get-SkillCategoryMeta -Category $category
        $lines.Add("- [$($meta.Title)](#$((($meta.Title).ToLower() -replace '[^a-z0-9 ]','' -replace '\s+','-'))) - $($group.Count) skills")
    }
}

$lines.Add("")
$lines.Add("## By Role")
$lines.Add("")

foreach ($skill in $skills) {
    $role = $skill.Frontmatter["role"]
    $roleGroups[$role] = @($roleGroups[$role]) + $skill.Slug
}

foreach ($role in $roleGroups.Keys) {
    $label = Get-SkillRoleLabel -Role $role
    $items = @($roleGroups[$role]) | Sort-Object
    if ($items.Count -gt 0) {
        $lines.Add("- $label：$([string]::Join(' / ', $items))")
    }
}

$lines.Add("")
$lines.Add("---")
$lines.Add("")

foreach ($category in $orderedCategories) {
    $group = $skills | Where-Object { $_.Frontmatter["category"] -eq $category } | Sort-Object Slug
    if (-not $group) {
        continue
    }

    $meta = Get-SkillCategoryMeta -Category $category
    $lines.Add("## $($meta.Emoji) $($meta.Title)")
    $lines.Add("")
    $lines.Add($meta.Description)
    $lines.Add("")

    foreach ($skill in $group) {
        $roleLabel = Get-SkillRoleLabel -Role $skill.Frontmatter["role"]
        $triggers = @($skill.Frontmatter["triggers"]) | Select-Object -First 3
        $related = @($skill.Frontmatter["related_skills"]) | Select-Object -First 4
        $constraints = @($skill.Frontmatter["constraints"]) | Select-Object -First 2

        $lines.Add("### $($skill.Slug)")
        $lines.Add("")
        $lines.Add("- 名称：$($skill.Frontmatter["name"])")
        $lines.Add("- 描述：$($skill.Frontmatter["description"])")
        $lines.Add("- 角色：$roleLabel")
        $lines.Add("- 触发：$([string]::Join(' / ', $triggers))")
        $lines.Add("- 关联：$([string]::Join(' / ', $related))")
        $lines.Add("- 约束：$([string]::Join(' / ', $constraints))")
        $lines.Add("- 路径：$($skill.RelativePath)")
        $lines.Add("")
    }

    $lines.Add("---")
    $lines.Add("")
}

$outputPath = Join-Path $repoRoot "SKILLS.md"
[System.IO.File]::WriteAllText($outputPath, [string]::Join([Environment]::NewLine, $lines) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath"
