function Get-SkillFrontmatter {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    $content = Get-Content $Path -Raw
    $match = [regex]::Match($content, '(?s)^---\r?\n(.*?)\r?\n---\r?\n?')
    if (-not $match.Success) {
        throw "Missing frontmatter: $Path"
    }

    $frontmatterText = $match.Groups[1].Value
    $body = $content.Substring($match.Length)
    $data = [ordered]@{}
    $currentArrayKey = $null

    foreach ($line in ($frontmatterText -split '\r?\n')) {
        if ($line -match '^([a-z_]+):\s*(.*)$') {
            $key = $Matches[1]
            $value = $Matches[2]
            if ([string]::IsNullOrWhiteSpace($value)) {
                $data[$key] = @()
                $currentArrayKey = $key
            } else {
                $data[$key] = $value.Trim()
                $currentArrayKey = $null
            }
            continue
        }

        if ($line -match '^\s*-\s+(.+)$' -and $null -ne $currentArrayKey) {
            $items = @($data[$currentArrayKey])
            $items += $Matches[1].Trim()
            $data[$currentArrayKey] = $items
        }
    }

    $absoluteRoot = (Resolve-Path $RepoRoot).Path
    $relativePath = (Resolve-Path $Path).Path.Substring($absoluteRoot.Length + 1).Replace('\', '/')
    if ($data.Contains("slug")) {
        $slug = $data["slug"]
    } else {
        $slug = [System.IO.Path]::GetFileName((Split-Path $Path -Parent))
    }
    $strippedBody = [regex]::Replace($body, '(?ms)```.*?```', '')

    return [pscustomobject]@{
        Path = $Path
        RelativePath = $relativePath
        Frontmatter = $data
        Body = $body
        StrippedBody = $strippedBody
        Slug = $slug
    }
}

function Get-SkillFiles {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    Get-ChildItem -Path $RepoRoot -Recurse -Filter "SKILL.md" | Sort-Object FullName
}

function Get-SkillCategoryMeta {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Category
    )

    switch ($Category) {
        "workflow" { return @{ Title = "Core Skills"; Emoji = "🧠"; Description = "通用流程与协作技能" } }
        "backend"  { return @{ Title = "Backend Skills"; Emoji = "🧩"; Description = "后端架构、接口与数据层技能" } }
        "frontend" { return @{ Title = "Frontend Skills"; Emoji = "🎨"; Description = "前端框架与界面工程技能" } }
        "language" { return @{ Title = "Language Skills"; Emoji = "🐹"; Description = "语言专项审查与地道实践技能" } }
        "ai"       { return @{ Title = "AI Skills"; Emoji = "🤖"; Description = "AI 辅助、提示词与文档生成技能" } }
        "utility"  { return @{ Title = "Utility Skills"; Emoji = "🔧"; Description = "工具类与仓库维护技能" } }
        default    { return @{ Title = "Other Skills"; Emoji = "📦"; Description = "未分类技能" } }
    }
}

function Get-SkillRoleLabel {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Role
    )

    switch ($Role) {
        "entrypoint" { return "入口" }
        "workflow"   { return "流程" }
        "specialist" { return "专项" }
        default      { return $Role }
    }
}

function Get-SkillCategoryOrder {
    return @("workflow", "backend", "frontend", "language", "ai", "utility")
}

function New-SkillIndexContent {
    param(
        [Parameter(Mandatory = $true)]
        [object[]]$Skills
    )

    $orderedCategories = Get-SkillCategoryOrder
    $lines = New-Object System.Collections.Generic.List[string]
    $roleGroups = [ordered]@{
        entrypoint = @()
        workflow   = @()
        specialist = @()
    }

    $coveredCategoryCount = @(
        foreach ($category in $orderedCategories) {
            if ($Skills | Where-Object { $_.Frontmatter["category"] -eq $category }) {
                $category
            }
        }
    ).Count

    $lines.Add("# Skill Index")
    $lines.Add("")
    $lines.Add('> Auto-generated by `scripts/generate-skills-index.ps1`. Do not edit manually.')
    $lines.Add("")
    $lines.Add("本目录包含当前项目可用的全部 Skills，用于辅助代码生成、规范约束与自动化决策。")
    $lines.Add("")
    $lines.Add("当前共收录 **$($Skills.Count)** 个 skills，覆盖 **$coveredCategoryCount** 个分类。")
    $lines.Add("")
    $lines.Add("## Quick Navigation")
    $lines.Add("")

    foreach ($category in $orderedCategories) {
        $group = $Skills | Where-Object { $_.Frontmatter["category"] -eq $category }
        if ($group) {
            $meta = Get-SkillCategoryMeta -Category $category
            $anchor = (($meta.Title).ToLower() -replace '[^a-z0-9 ]','' -replace '\s+','-')
            $lines.Add("- [$($meta.Title)](#$anchor) - $($group.Count) skills")
        }
    }

    $lines.Add("")
    $lines.Add("## By Role")
    $lines.Add("")

    foreach ($skill in $Skills) {
        $role = $skill.Frontmatter["role"]
        $roleGroups[$role] = @($roleGroups[$role]) + $skill.Slug
    }

    foreach ($role in $roleGroups.Keys) {
        $label = Get-SkillRoleLabel -Role $role
        $items = @($roleGroups[$role]) | Sort-Object
        if ($items.Count -gt 0) {
            $lines.Add("- $label：$([string]::Join(' / ', $items))")
        }
    }

    $lines.Add("")
    $lines.Add("---")
    $lines.Add("")

    foreach ($category in $orderedCategories) {
        $group = $Skills | Where-Object { $_.Frontmatter["category"] -eq $category } | Sort-Object Slug
        if (-not $group) {
            continue
        }

        $meta = Get-SkillCategoryMeta -Category $category
        $lines.Add("## $($meta.Emoji) $($meta.Title)")
        $lines.Add("")
        $lines.Add($meta.Description)
        $lines.Add("")

        foreach ($skill in $group) {
            $roleLabel = Get-SkillRoleLabel -Role $skill.Frontmatter["role"]
            $triggers = @($skill.Frontmatter["triggers"]) | Select-Object -First 3
            $related = @($skill.Frontmatter["related_skills"]) | Select-Object -First 4
            $constraints = @($skill.Frontmatter["constraints"]) | Select-Object -First 2

            $lines.Add("### $($skill.Slug)")
            $lines.Add("")
            $lines.Add("- 名称：$($skill.Frontmatter["name"])")
            $lines.Add("- 描述：$($skill.Frontmatter["description"])")
            $lines.Add("- 角色：$roleLabel")
            $lines.Add("- 触发：$([string]::Join(' / ', $triggers))")
            $lines.Add("- 关联：$([string]::Join(' / ', $related))")
            $lines.Add("- 约束：$([string]::Join(' / ', $constraints))")
            $lines.Add("- 路径：$($skill.RelativePath)")
            $lines.Add("")
        }

        $lines.Add("---")
        $lines.Add("")
    }

    return [string]::Join("`n", $lines) + "`n"
}
